[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-math="0.1.1"
rayon="1.8.0"
glfw="*"
gl="0.14.0"
imgui="0.11.0"
imgui-glfw-rs = "0.4.1"
image="0.24.7"
tobj="*"