[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-math="0.1.1"
rayon="1.8.0"
glfw="*"
gl="*"
imgui="*"
imgui-glfw-rs = "0.4.1"